kind: Service
apiVersion: v1
metadata:
  name: rollout-bluegreen-active
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-wave: "7"  
spec:
  selector:
    app: rollout-bluegreen
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 5000
  type: LoadBalancer

