apiVersion: argoproj.io/v1alpha1     
kind: Rollout  
metadata:
  name: rollout-bluegreen
  namespace: prod
  # annotations:
  #   argocd.argoproj.io/sync-wave: "6" 
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: rollout-bluegreen
  template:
    metadata:
      labels:
        app: rollout-bluegreen
    spec:
      containers:
        - name: rollouts-demo
          # image: gowdasagar/flaskapp:latest
          image: gowdasagar/2tier-blue-green:green
          # image: gowdasagar/2tier-blue-green:blue
          env:
            - name: MYSQL_HOST
              value: mysql          
            - name: MYSQL_PASSWORD
              value: "admin"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_DB
              value: "mydb"
          ports:
            - containerPort: 5000
          imagePullPolicy: Always
  strategy:
    blueGreen: 
      activeService: rollout-bluegreen-active 
      previewService: rollout-bluegreen-preview
      autoPromotionEnabled: false


