apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
  - https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

resources:
  - namespace.yml
  - mysql-configmap.yml
  - mysql-secrets.yml
  - storage-ebs.yml
  - pvc-ebs.yml
  - mysql-deployment.yml
  - mysql-svc.yml
  - two-tier-app-deployment.yml
  - two-tier-app-svc.yml
  - deployment.yaml
  - active-service.yaml
  - preview-service.yaml

  
 
 
