---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 3-tier-app
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-failed.slack: alerts
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: alerts
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/gowdasagar06/ArgoCD-3-Tier-Deployment.git
    targetRevision: HEAD
    path: my-app
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      #prune: true
        #selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
