apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- namespace.yaml
- secret.yaml
- pv.yaml
- pvc.yaml
- statefulset.yaml
- sqlservice.yaml
- mattermost.yaml
- nginx.yaml
