apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prod
resources:
- namespace.yaml
- secret.yaml
- storage-ebs.yaml
- pvc-ebs.yaml
- statefulset.yaml
- sqlservice.yaml
- mattermost.yaml
- nginx.yaml
