apiVersion: v1 
kind: Secret 
metadata:
  name: mysecret
  namespace: prod
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
stringData:
   ROOT_PASSWORD: Sagar@123
   MYSQL_DATABASE: mattermost 
