kind: Service
apiVersion: v1
metadata:
  name: rollout-ngnix-active # <- active 
  namespace: argo-rollouts
spec:
  selector:
    app: ngnix
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
