kind: Service
apiVersion: v1
metadata:
  name: rollout-ngnix-preview # <- preview
  namespace: argo-rollouts
spec:
  type: LoadBalancer
  selector:
    app: ngnix
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

